# GÉNERO REGGETON PARA 2010-2015

In [3]:
import pandas as pd
import json
import requests
import os

In [4]:
with open('definitivo.json') as archivo: 
    data = json.load(archivo)

In [5]:
data

[{'id': '7AlYBA5M9FVXDqN31cbExE',
  'artist_name': 'Remedios Amaya',
  'track_name': 'El zarandeo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4uqcES2h19TKAXQlciycrO',
  'artist_name': 'Nobuo Uematsu',
  'track_name': "Vamo'alla flamenco",
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0z6xGK2u3nSsbk9XeKYwZQ',
  'artist_name': 'Maurice Ravel',
  'track_name': 'Flamenco Bolero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6DjfWx0fXi0uQpedpvaCD9',
  'artist_name': 'Mark Towns',
  'track_name': 'After the Rain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1t91qQaPbOoo4pumaLih4W',
  'artist_name': 'Franz Schubert',
  'track_name': 'Tango Serenata (Ständchen)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7Kuasu0H7jArcADoFIHGUk',
  'artist_name': 'Mark Towns',
  'track_name': 'Corriente',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '02jM23k8pgm9gcZpyIn8Wk',
  'artist_name': 'Georges Moustaki',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2tnnbPGlhpY1420firAE7v',
  'artist_name': 'El Arrebato',
  'track_name': 'Rumba Canalla',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5OFZgm7YRtEHkoUdgIdMhF',
  'artist_name': 'Mark Towns',
  'track_name': 'Medley: The Way/La Via',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3dVVMsZCVGxce42Nd9a0XC',
  'artist_name': 'Tomaso Albinoni',
  'track_name': 'Tango Adagio',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4EOgdSxqtZZGvOrzuyQAGz',
  'artist_name': 'Johann Pachelbel',
  'track_name': 'Soleá Canon',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73KHkT0m5CW2xWgJAxCmoA',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, con baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1xikd54XPRJeJwRIv0yIzO',
  'artist_name': 'Mark Towns',
  'track_name': 'Sabrosa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0sKS1f30oQdGw903RR7fBN',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2eLniDU3Fbg6QUTbreLUrF',
  'artist_name': 'Márquez El Zapatero',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo de Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77242gtA1Jymsu2Vl9LGxR',
  'artist_name': 'Rocio Ruiz',
  'track_name': 'Flamenco,Cante por Martinete',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5YKBLRuQrbRDyrJaH7nywI',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, sin baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6mpQYMq1l1gU0ltQ0nO1IW',
  'artist_name': 'Antonio Vivaldi',
  'track_name': 'Primavera Tango (Four Seasons)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5pG5LCEvPX175P4ukUCFmR',
  'artist_name': 'La Carmen',
  'track_name': 'Flamencos a volar',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5qhcnvZmA4lm7fClwUbGwB',
  'artist_name': 'Enaldo Barrera',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XNVIE3jSJUoGzehQN9m9g',
  'artist_name': 'Chano Lobato',
  'track_name': 'Tanguillos de Cádiz',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6Nm0bBmYBI74CyApeaVZhF',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Rumba Allegro (Symphony no.40)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2L2ObU16rqwFvOIfbseBLX',
  'artist_name': 'Chiqui de Jerez',
  'track_name': 'El Teléfono de Mi Casa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2w6JLw4LmLEl57uUKhRldQ',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 190',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2edeklaJKKKx9ZyxDD2bSG',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Moonlight Rumba (Moonlight Sonata)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '71AKM5R1HijC743bGDWJBy',
  'artist_name': 'Mark Towns',
  'track_name': 'Merengue Gitano',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6dOwfELGupyrMHzkVegViT',
  'artist_name': 'Mark Towns',
  'track_name': 'Selva Urbana',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MJgtHcv1Wjv4Wxc9nJATo',
  'artist_name': 'Johann Sebastian Bach',
  'track_name': 'Tango Aria (Air on the G String)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2zEhscbOlOC6Bl6OVcWfL1',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo Compás 132',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6l2HTLRp8mTasMXOtvFEhb',
  'artist_name': 'Mark Towns',
  'track_name': 'Chucho',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5PGy4rzoVYQwMTfa4Svvgr',
  'artist_name': 'Levantito',
  'track_name': 'El Jardín de Mis Sueños',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5xA7tKg7QPsvAUVWap88rN',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Fandango for Elise (Für Elise)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1OkfxOngQIpLS7atBmCQSQ',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Media (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3QnvDtqgg8KGq8QypBbsv0',
  'artist_name': 'Dorantes',
  'track_name': 'Orobroy',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XvJsSuXS1iZxlpYojYj0W',
  'artist_name': 'Felix Mendelssohn',
  'track_name': 'Andante Rumba (Symphony 5)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZfMZkSi4itskqn6PNNBAc',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Rápida (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1AaqOJEurORS9gIjdeEHTD',
  'artist_name': 'Mark Towns',
  'track_name': 'Wondering',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0R3lPDIKv89qWEmYWTIoNE',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Bulería Adagio (Piano Concerto No.21)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1CVS0YLa7YpB4wRIQYiJPf',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 225',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ro8lFaoIHAv2chG3hq4xg',
  'artist_name': 'La Macanita',
  'track_name': 'Cantiñas del Marinero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5zNOlWjHpmZymXQ7jvxq1T',
  'artist_name': 'Mark Towns',
  'track_name': 'Like the Wind',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55fV0QtDYtaLfB3aTID6RF',
  'artist_name': 'Mark Towns',
  'track_name': 'Wind on the Mountain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cH2C7YxjpZQ7yhEwjs2AW',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos con baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '14mstquH2GHwuYmVp9qL1y',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Granaina: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5GW7kNyJpij82MhhnkIqAA',
  'artist_name': 'Traditional',
  'track_name': 'Medina Azahara (Granainas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZWMF5j3taR7DESgZLq8FU',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Lentas (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0d92SBPncK0zSR6IzhXxIM',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Surrender 2 Love - 2000 Remastered',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0kruq9DXxP9Lm0PdfbYBs0',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Medias (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bZvLAST6NXKOVBOocVzPr',
  'artist_name': 'Traditional',
  'track_name': 'Acera del Rio (Soleares)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0aberAzTHOxf4XH1JeUfnK',
  'artist_name': 'Traditional',
  'track_name': 'Salobre (Malagueñas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IMAOBRpQt9NLxheodkd18',
  'artist_name': 'Chonchi Heredia',
  'track_name': 'El Camino de Mi Destino',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1ggH47au252TP4T692rE0T',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'After The Rain - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77tmRwrSvrvHEHqku7OpXT',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Barcelona Nights - 2000 Digital Remaster',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4FsDuVJo6xLs8XTbdLP49D',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Malagueña: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '32aXQMl5U8lsVqk4n12waz',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 246',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jcdqacg2QJ3GHQujEuR5H',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 260',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jig5Z8KciCU2QXmnCBnnc',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Media (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5jsifLClBCWoE1nlasPiZh',
  'artist_name': 'Traditional',
  'track_name': 'Los Veleros (Alegrías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZPVwZFwsJ9SpcyEhrEBBR',
  'artist_name': 'Traditional',
  'track_name': 'Cancion (Peteneras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6ZFNcrtjNOn9bGrlPgnvt7',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Rondeña',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '28CDw1t8f0LwNQ0X3aUrGV',
  'artist_name': 'Ana Salazar',
  'track_name': 'Tu Eres para Mi',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '16UK3SdKxsyQojGZ2Xzn7u',
  'artist_name': 'Traditional',
  'track_name': 'Solquema (Bulerías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4JoAqRjk6ZbyYbSfTiKSVu',
  'artist_name': 'Traditional',
  'track_name': 'Mantilla y Peina (Guajiras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2NUssxdoSQRkZYyZykmnLb',
  'artist_name': 'Mark Towns',
  'track_name': 'Salamanca',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '314x76MVwlmB76sL1VMON2',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos sin baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '30xWhibl7o3ki0DsldxXr6',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 234',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6CGcj8K2ZZdPWqUbyJjxMK',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Cantes de Levante: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2qiy4xV66GJOllkMaPDD3M',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Peteneras: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4Z7Uf6yZA3Vqb0NED9c71j',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Rápida (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '593pSt7bzylRcc7CcsHqUK',
  'artist_name': 'El Trini',
  'track_name': 'Zambra: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0lxBV7AmHRY5uIWgR5ywtb',
  'artist_name': 'El Trini',
  'track_name': 'Fandangos Naturales: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79wfu1liWB4PZszqmQJuEu',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0pPUllW2drfZeyFF50aQp7',
  'artist_name': 'Traditional',
  'track_name': 'Riomar (Fandangos de Huelva)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cr6W8t5INBKw7zSupZY8R',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Farrucas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '515ndth3zLBPv4SY6JkJEZ',
  'artist_name': 'Los Activos',
  'track_name': 'Divertimiento Callejero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '38NCXxFi771HBggW1EC8If',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Granaína',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77yb0X5ESIBmkVYxlRZzO5',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Soléa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cvP0pwydWW64Akm14VlXs',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Zambra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ADzQCu8UnyZAnBie5bV57',
  'artist_name': 'Manuel de Angustias',
  'track_name': 'Te Tengo Que Querer',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1QESy53hSMNaiaNbmbBNuE',
  'artist_name': 'Traditional',
  'track_name': 'Claroscuro (Tangos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7oQQuYMbQBBtzSHMRKUXju',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Fandangos',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5A8FVt6fFmsXIRVIYD4iEG',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Tango - mayor y menor',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3Y2exCd1xymfuTmD9611BO',
  'artist_name': 'Ramon Montoya',
  'track_name': '"La Rosa" - Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6J7QoPhijQk8A0RLUvInFe',
  'artist_name': 'Mark Towns',
  'track_name': 'Touch',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2jSNj63K0JiyjA2q7UszKd',
  'artist_name': 'Traditional',
  'track_name': 'Las Ferialas (Sevillanas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6qZpjbbfNC8E3Efr70nIku',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Bulerías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6JTyUehuFzwzFZgCK3Wksj',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Tarantas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5UycZV2sto9vywMtNGzYYT',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3nWHz7o8trM4gwRrlx8wpu',
  'artist_name': 'Traditional',
  'track_name': 'Puerto Aguila (Tientos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5Tn3I3OYCPmZE4Adizv0HD',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Minera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2FNZ1W6NQJ6i2oaS9wNvil',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Seguiriyas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4csZty0AxR9WAIWVCDLjR5',
  'artist_name': 'Traditional',
  'track_name': 'Pedregales (Serranas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '48XjQujCABfBTZKi3j6pr9',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Santa Fe - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bUmOYqEMPGiv3gFJ2jB30',
  'artist_name': 'El Trini',
  'track_name': 'Toná: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IN6Zi7yjbeVK069J3QUEn',
  'artist_name': 'El Trini',
  'track_name': 'Debla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MyvQtdefpdadVUgGm4JD4',
  'artist_name': 'Acoustic Alchemy',
  'track_name': 'The Last Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4B55Q4PWuniTmPFr1Opw2Y',
  'artist_name': '植松 伸夫',
  'track_name': 'Vamo alla Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3yIsUXghgtMK3MuWVTsdsc',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Passing Storm - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0vqOXN6bhA4nWNjB5M5YuI',
  'artist_name': 'El Trini',
  'track_name': 'Livianas: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1uLokmb1H3AEfYM7K48DUY',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Rápida Cuatro Cuerpos (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3zLYx27eMIRdlw8xDMeIP7',
  'artist_name': 'El Trini',
  'track_name': 'Martinete: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1izTZlIOJCgHOaGJMoyr6N',
  'artist_name': 'El Trini',
  'track_name': 'Serrana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6OFw0tKxEAxkYnC5Qnfu6P',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Boleras (Guitarra, Laud y Bandurria)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0t27O9Fk0I0T1mRdJbE2Mz',
  'artist_name': 'El Trini',
  'track_name': 'Nana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79EWFLYoVfEUyzjNVVQIwJ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 120',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4369URVfz7QM9AwKqYz5nd',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6QshtnzwUzZsMkrPm3UkcZ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 160',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2pQ6wESsjj5mEKBAibYFat',
  'artist_name': 'El Trini',
  'track_name': 'Granaina y Media Granaina: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7uHQvzFgU7ViE8ES0qR3pc',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '26dXN84ePUqIHuR6e40D6E',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3lD2mjspXgh3hkIdrJuRZQ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4caAGy3SvHorRmh9RSFFd2',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6et3COTopxtId4gCpElGaU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4s8VgVoI16ILUFVXNDFZpl',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3KHA7uGRQrft6goXandJGU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3skYj3zKvIOXArFlT5h1aY',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 140',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7vr6MibrK67KqENxb6WKU8',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1SRAiujmU4mmYfF3mBDHP9',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '06stEj7Zoupi6o3lOD7vfx',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2VU3v2sjK6yg98fv0mG8MU',
  'artist_name': 'Ottmar Liebert',
  'track_name': '3 Women Walking - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3BfsufA6s2iPAmhTgmJ2HH',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Media (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1oWz1iu6eyOpc5u6AGHQU1',
  'artist_name': 'El Trini',
  'track_name': 'Trilla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55H080ETLO2D4787FpTCHv',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5XBXF86fIWxYLDpEzMfw8z',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 220',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1DzMgYzPaH4H6ugXNAfWFv',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'El Angelito',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2BLUSXzTKkp9yJ54ELJSLT',
  'artist_name': 'Ottmar Liebert',
  'track_name': '2 The Night - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6UvU9cOu3MjWbDxiF2h3ug',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Que bonita va',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1n1Cr82fHJ7dg1n6VPGD5V',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Moon Over Trees - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73XZI6jT8OKrCikrK7EYK4',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Un año de espera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2DVp3fA4JwfYseQU9wR67W',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Cohetes en el aire',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4SRtBNkq160IcE1Z8zRDmG',

In [6]:
filtrado_datos = []

In [7]:
for d in data:
    if d["genre"] == "reggaeton" and 2013 <= int(d["year"]) <= 2015:
        filtrado_datos.append(d)

In [8]:
filtrado_datos

[{'id': '1hvf4GP5GbVQ8aPbVXIsEW',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '46lg4dxjDyig9MVX271szQ',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '4ApSXhiRpboS6M8e0kg9Jq',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '36rH4mPe87uobaXzb5uPNG',
  'artist_name': 'Midiland',
  'track_name': 'Renegade Dancers - Version Dance',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '1KqCw7AwVIgRJAIBgH1poL',
  'artist_name': 'Los Flechazos',
  'track_name': 'Suzette',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '318HbfUmnbbZ9C0wmF4Hf0',
  'artist_name': 'Kamembert',
  'track_name': 'Sha la la',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Don Latino',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Crossfire',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '7vHIaYACvYiyzSvP55QqU5',
  'artist_name': 'Corban Urban',
  'track_name': 'Alabarte',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Freeway',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Memphis Bleek',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Just Blaze',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0LJhox6uOMtrHtLKbZ8gLm',
  'artist_name': 'Peter Polycarpou',
  'track_name': 'Chapter 1',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '30OgJClocf3npT0SZIbCiy',
  'artist_name': 'Kryss',
  'track_name': 'Tonight',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2yrcjgxdcMpdA8JvOLVKGl',
  'artist_name': 'Hanson',
  'track_name': 'MMMBop',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kriss',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'B.P.M. System',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Omega',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kike Boy',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'High Density',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Megabass',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4YBFDSBQtoK2zUNsN9FTZg',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0OQ5SqE5KkpY639bq5uFFO',
  'artist_name': 'The Style Council',
  'track_name': 'Shout To The Top',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5FIUKOSQ2kiE0ad7GxCrO9',
  'artist_name': 'Squeeze',
  'track_name': 'Tempted',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4g0mYcIWlORX07UV3fwxzQ',
  'artist_name': 'Iggy Pop',
  'track_name': 'Candy',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5eJdszTnAudulQT3zcvsrQ',
  'artist_name': 'The Nativos',
  'track_name': 'Night Time',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2gENHmajLeR1vFSGCtkaLn',
  'artist_name': 'Jerry Daley',
  'track_name': 'Gold - "F" Mix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Brian Cross',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Fat Synth',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3J3CmUhlNjqWaokvikdTXM',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Radio Cut',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '7GAfhe7K6ZAp0J9ncdh5tD',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Sven-R-G vs. Bass-T Club Mix',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0iNU5DNKXowDDoBcggClv4',
  'artist_name': '2 In A Room',
  'track_name': 'Now',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Brian Cross',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Fat Synth',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Brian Cross',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Fat Synth',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '2dU2I8cJAvg4v9uTKWmoot',
  'artist_name': 'Generis',
  'track_name': 'Dreams',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '20WRbAfJhdDpY5iP2xfCI3',
  'artist_name': 'Fiesta Pop',
  'track_name': 'Año 2000',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '4VoHWTKwdeejTOEDXG1QCc',
  'artist_name': 'Fiesta Pop',
  'track_name': 'A Quien Le Importa',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0il4GDOrhu9x0NXboG5P7V',
  'artist_name': 'Korpus',
  'track_name': 'Indie',
  'genre': 'reggaeton',
  'year': 2015}]

In [9]:
filtrado_datos = []

In [10]:
for d in data:
    if d["genre"] == "reggaeton" and 2013 <= int(d["year"]) <= 2015:
        filtrado_datos.append(d)

In [11]:
filtrado_datos

[{'id': '1hvf4GP5GbVQ8aPbVXIsEW',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '46lg4dxjDyig9MVX271szQ',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '4ApSXhiRpboS6M8e0kg9Jq',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '36rH4mPe87uobaXzb5uPNG',
  'artist_name': 'Midiland',
  'track_name': 'Renegade Dancers - Version Dance',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '1KqCw7AwVIgRJAIBgH1poL',
  'artist_name': 'Los Flechazos',
  'track_name': 'Suzette',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '318HbfUmnbbZ9C0wmF4Hf0',
  'artist_name': 'Kamembert',
  'track_name': 'Sha la la',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Don Latino',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Crossfire',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '7vHIaYACvYiyzSvP55QqU5',
  'artist_name': 'Corban Urban',
  'track_name': 'Alabarte',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Freeway',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Memphis Bleek',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Just Blaze',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0LJhox6uOMtrHtLKbZ8gLm',
  'artist_name': 'Peter Polycarpou',
  'track_name': 'Chapter 1',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '30OgJClocf3npT0SZIbCiy',
  'artist_name': 'Kryss',
  'track_name': 'Tonight',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2yrcjgxdcMpdA8JvOLVKGl',
  'artist_name': 'Hanson',
  'track_name': 'MMMBop',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kriss',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'B.P.M. System',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Omega',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kike Boy',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'High Density',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Megabass',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4YBFDSBQtoK2zUNsN9FTZg',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0OQ5SqE5KkpY639bq5uFFO',
  'artist_name': 'The Style Council',
  'track_name': 'Shout To The Top',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5FIUKOSQ2kiE0ad7GxCrO9',
  'artist_name': 'Squeeze',
  'track_name': 'Tempted',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4g0mYcIWlORX07UV3fwxzQ',
  'artist_name': 'Iggy Pop',
  'track_name': 'Candy',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5eJdszTnAudulQT3zcvsrQ',
  'artist_name': 'The Nativos',
  'track_name': 'Night Time',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2gENHmajLeR1vFSGCtkaLn',
  'artist_name': 'Jerry Daley',
  'track_name': 'Gold - "F" Mix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Brian Cross',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Fat Synth',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3J3CmUhlNjqWaokvikdTXM',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Radio Cut',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '7GAfhe7K6ZAp0J9ncdh5tD',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Sven-R-G vs. Bass-T Club Mix',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0iNU5DNKXowDDoBcggClv4',
  'artist_name': '2 In A Room',
  'track_name': 'Now',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Brian Cross',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Fat Synth',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Brian Cross',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Fat Synth',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '2dU2I8cJAvg4v9uTKWmoot',
  'artist_name': 'Generis',
  'track_name': 'Dreams',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '20WRbAfJhdDpY5iP2xfCI3',
  'artist_name': 'Fiesta Pop',
  'track_name': 'Año 2000',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '4VoHWTKwdeejTOEDXG1QCc',
  'artist_name': 'Fiesta Pop',
  'track_name': 'A Quien Le Importa',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0il4GDOrhu9x0NXboG5P7V',
  'artist_name': 'Korpus',
  'track_name': 'Indie',
  'genre': 'reggaeton',
  'year': 2015}]

In [12]:
anios = [2013, 2014, 2015]
genres = ['reggaeton']

In [13]:
canciones_filtrada = []

for cancion in data:
    if cancion['genre'] in genres:
        if cancion['year'] in anios:
            canciones_filtrada.append(cancion)

canciones_filtrada

[{'id': '1hvf4GP5GbVQ8aPbVXIsEW',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '46lg4dxjDyig9MVX271szQ',
  'artist_name': 'McFly',
  'track_name': 'McFly The Musical - Live At The Royal Albert Hall',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '4ApSXhiRpboS6M8e0kg9Jq',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '36rH4mPe87uobaXzb5uPNG',
  'artist_name': 'Midiland',
  'track_name': 'Renegade Dancers - Version Dance',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '1KqCw7AwVIgRJAIBgH1poL',
  'artist_name': 'Los Flechazos',
  'track_name': 'Suzette',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '318HbfUmnbbZ9C0wmF4Hf0',
  'artist_name': 'Kamembert',
  'track_name': 'Sha la la',
  'genre': 'reggaeton',
  'year': 2013},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Don Latino',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5xiHRwTo3PiPjMg62oaJjL',
  'artist_name': 'Crossfire',
  'track_name': 'Tuku Taka - Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '7vHIaYACvYiyzSvP55QqU5',
  'artist_name': 'Corban Urban',
  'track_name': 'Alabarte',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Freeway',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Memphis Bleek',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '60khFr0gE03gfb78q5gyRW',
  'artist_name': 'Just Blaze',
  'track_name': "Let's Go",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0LJhox6uOMtrHtLKbZ8gLm',
  'artist_name': 'Peter Polycarpou',
  'track_name': 'Chapter 1',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '30OgJClocf3npT0SZIbCiy',
  'artist_name': 'Kryss',
  'track_name': 'Tonight',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2yrcjgxdcMpdA8JvOLVKGl',
  'artist_name': 'Hanson',
  'track_name': 'MMMBop',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kriss',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'B.P.M. System',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Omega',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Kike Boy',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'High Density',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '072RMxyaiPGuUfop8jAemH',
  'artist_name': 'Megabass',
  'track_name': "Tecnologico III Megamix / Tonight / C'est Si Bon / Transformer / Jumper / Label Remix / This D.J. Is .....",
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4YBFDSBQtoK2zUNsN9FTZg',
  'artist_name': 'Tess',
  'track_name': 'The Second That You Sleep - Interphace Remix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '0OQ5SqE5KkpY639bq5uFFO',
  'artist_name': 'The Style Council',
  'track_name': 'Shout To The Top',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5FIUKOSQ2kiE0ad7GxCrO9',
  'artist_name': 'Squeeze',
  'track_name': 'Tempted',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '4g0mYcIWlORX07UV3fwxzQ',
  'artist_name': 'Iggy Pop',
  'track_name': 'Candy',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '5eJdszTnAudulQT3zcvsrQ',
  'artist_name': 'The Nativos',
  'track_name': 'Night Time',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '2gENHmajLeR1vFSGCtkaLn',
  'artist_name': 'Jerry Daley',
  'track_name': 'Gold - "F" Mix',
  'genre': 'reggaeton',
  'year': 2014},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Brian Cross',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '48lpqgtWVMIgohPXykr0Q9',
  'artist_name': 'Fat Synth',
  'track_name': 'The Emotions',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3J3CmUhlNjqWaokvikdTXM',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Radio Cut',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '7GAfhe7K6ZAp0J9ncdh5tD',
  'artist_name': '2001:Canarias',
  'track_name': 'Comin Up Strong - Sven-R-G vs. Bass-T Club Mix',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0iNU5DNKXowDDoBcggClv4',
  'artist_name': '2 In A Room',
  'track_name': 'Now',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Brian Cross',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '1aQXvB2MrsoJznI5wldosb',
  'artist_name': 'Fat Synth',
  'track_name': 'The Eyes',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Brian Cross',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '3ob8TbTdg3zm0fe5KCGg30',
  'artist_name': 'Fat Synth',
  'track_name': 'Secret',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '2dU2I8cJAvg4v9uTKWmoot',
  'artist_name': 'Generis',
  'track_name': 'Dreams',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '20WRbAfJhdDpY5iP2xfCI3',
  'artist_name': 'Fiesta Pop',
  'track_name': 'Año 2000',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '4VoHWTKwdeejTOEDXG1QCc',
  'artist_name': 'Fiesta Pop',
  'track_name': 'A Quien Le Importa',
  'genre': 'reggaeton',
  'year': 2015},
 {'id': '0il4GDOrhu9x0NXboG5P7V',
  'artist_name': 'Korpus',
  'track_name': 'Indie',
  'genre': 'reggaeton',
  'year': 2015}]

In [14]:
#para ver los artistas que hay sin duplicados
artistas_unicos = sorted({d["artist_name"] for d in filtrado_datos})
len(artistas_unicos), artistas_unicos[:59]

(32,
 ['2 In A Room',
  '2001:Canarias',
  'B.P.M. System',
  'Brian Cross',
  'Corban Urban',
  'Crossfire',
  'Don Latino',
  'Fat Synth',
  'Fiesta Pop',
  'Freeway',
  'Generis',
  'Hanson',
  'High Density',
  'Iggy Pop',
  'Jerry Daley',
  'Just Blaze',
  'Kamembert',
  'Kike Boy',
  'Korpus',
  'Kriss',
  'Kryss',
  'Los Flechazos',
  'McFly',
  'Megabass',
  'Memphis Bleek',
  'Midiland',
  'Omega',
  'Peter Polycarpou',
  'Squeeze',
  'Tess',
  'The Nativos',
  'The Style Council'])

# BUSCAR EN LAST.FM

In [15]:
url = f"http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Cher&api_key=YOUR_API_KEY&format=json"
api_key = "2ba5fcc50d41ca65db0713b4d0cd13a3"

In [16]:
datos_artista = []

for artista in artistas_unicos:
    url = "https://ws.audioscrobbler.com/2.0"

    llamada = requests.get(url, params={'api_key': api_key,
                                        'method': 'artist.getinfo',
                                        'artist': {artista},
                                        'format': 'json'})
    datos = llamada.json()
    datos_artista.append(datos)

In [17]:
datos_artista

[{'artist': {'name': '2 In A Room',
   'url': 'https://www.last.fm/music/2+In+A+Room',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}],
   'streamable': '0',
   'ontour': '0',
   'stats': {'listeners': '29985', 'playcount': '117726'},
   'similar': {'artist': [{'name': '49ers',
      'url': 'https://www.last.fm/music/49ers',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Black Box',
      'url': 'https://www.last.fm/music/Black+Box',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Technotronic',
      'url': 'https://www.last.fm/music/Technotronic',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Adamski',
      'url': 'https://www.last.fm/music/Adamski',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Snap!',
      'url': 'https://www.last.fm/music/Snap%21',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]}]},
   'tags': {'tag': [{'name': 'House', 'url': 'https://www.last.fm/tag/House'},
     {'name': 'dance', 'url': 'https://www.last.fm/tag/dance'},
     {'name': 'electronic', 'url': 'https://www.last.fm/tag/electronic'},
     {'name': 'USA', 'url': 'https://www.last.fm/tag/USA'},
     {'name': 'hip house', 'url': 'https://www.last.fm/tag/hip+house'}]},
   'bio': {'links': {'link': {'#text': '',
      'rel': 'original',
      'href': 'https://last.fm/music/2+In+A+Room/+wiki'}},
    'published': '15 May 2006, 23:33',
    'summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits) <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>',
    'content': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits), but they did chart several more singles on the dance chart through the nineties.\n\nTheir first release in the UK was "Somebody In The House Say Yeah!" in the late part of 1989. <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}},
 {'artist': {'name': '2001:Canarias',
   'url': 'https://www.last.fm/music/+noredirect/2001:Canarias',
   'image': [{'#text': '', 'size': 'small'},
    {'#text': '', 'size': 'medium'},
    {'#text': '', 'size': 'large'},
    {'#text': '', 'size': 'extralarge'},
    {'#text': '', 'size': 'mega'},
    {'#text': '', 'size': ''}],
   'streamable': '0',
   'ontour': '0',
   'stats': {'listeners': '267', 'playcount': '879'},
   'similar': {'artist': []},
   'tags': {'tag': []},
   'bio': {'links': {'link': {'#text': '',
      'rel': 'original',
      'href': 'https://last.fm/music/+noredirect/2001:Canarias/+wiki'}},
    'published': '01 Jan 1970, 00:00',
    'summary': ' <a href="https://www.last.fm/music/+noredirect/2001:Canarias">Read more on Last.fm</a>',
    'content': ''}}},
 {'artist': {'name': 'B.P.M. System',
   'url': 'https://www.last.fm/music/B.P.M.+System',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}],
   'streamable': '0',
   'ontour': '0',
   'stats': {'listeners': '1414', 'playcount': '6773'},
   'similar': {'artist': [{'name': 'Lady Gee',
      'url': 'https://www.last.fm/music/Lady+Gee',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Kike Boy',
      'url': 'https://www.last.fm/music/Kike+Boy',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Kryss',
      'url': 'https://www.last.fm/music/Kryss',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'New Limit',
      'url': 'https://www.last.fm/music/New+Limit',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Interfront',
      'url': 'https://www.last.fm/music/Interfront',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]}]},
   'tags': {'tag': [{'name': 'electronic',
      'url': 'https://www.last.fm/tag/electronic'},
     {'name': 'dance', 'url': 'https://www.last.fm/tag/dance'}]},
   'bio': {'links': {'link': {'#text': '',
      'rel': 'original',
      'href': 'https://last.fm/music/B.P.M.+System/+wiki'}},
    'published': '01 Jan 1970, 00:00',
    'summary': ' <a href="https://www.last.fm/music/B.P.M.+System">Read more on Last.fm</a>',
    'content': ''}}},
 {'artist': {'name': 'Brian Cross',
   'mbid': 'c27204ac-b529-4ef1-940e-5d3c6eac1c10',
   'url': 'https://www.last.fm/music/Brian+Cross',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}],
   'streamable': '0',
   'ontour': '0',
   'stats': {'listeners': '29255', 'playcount': '126016'},
   'similar': {'artist': [{'name': 'DJ Nano',
      'url': 'https://www.last.fm/music/DJ+Nano',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Dani Moreno',
      'url': 'https://www.last.fm/music/Dani+Moreno',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Jose AM',
      'url': 'https://www.last.fm/music/Jose+AM',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Wally Lopez',
      'url': 'https://www.last.fm/music/Wally+Lopez',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]},
     {'name': 'Geo Da Silva & Saftik',
      'url': 'https://www.last.fm/music/Geo+Da+Silva+&+Saftik',
      'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'small'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'medium'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'large'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'extralarge'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': 'mega'},
       {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
        'size': ''}]}]},
   'tags': {'tag': [{'name': 'trance',
      'url': 'https://www.last.fm/tag/trance'},
     {'name': 'progressive trance',
      'url': 'https://www.last.fm/tag/progressive+trance'},
     {'name': 'House', 'url': 'https://www.last.fm/tag/House'},
     {'name': 'electronic', 'url': 'https://www.last.fm/tag/electronic'},
     {'name': 'spanish', 'url': 'https://www.last.fm/tag/spanish'}]},
   'bio': {'links': {'link': {'#text': '',
      'rel': 'original',
      'href': 'https://last.fm/music/Brian+Cross/+wiki'}},
    'published': '27 May 2008, 22:21',

In [18]:
datos_artista[0].keys()

dict_keys(['artist'])

In [19]:
datos_artista[0]['artist'].keys()

dict_keys(['name', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [20]:
datos_artista[0]['artist']['stats']

{'listeners': '29985', 'playcount': '117726'}

In [21]:
datos_artista[0]['artist']['bio']

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/2+In+A+Room/+wiki'}},
 'published': '15 May 2006, 23:33',
 'summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits) <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>',
 'content': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits), but they did chart several more singles on the dance chart through the nineties.\n\nTheir first release in the UK was "Somebody In The House Say Yeah!" in the late part of 1989. <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [22]:
datos_artista[0]['artist']['similar']

{'artist': [{'name': '49ers',
   'url': 'https://www.last.fm/music/49ers',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Black Box',
   'url': 'https://www.last.fm/music/Black+Box',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Technotronic',
   'url': 'https://www.last.fm/music/Technotronic',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Adamski',
   'url': 'https://www.last.fm/music/Adamski',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Snap!',
   'url': 'https://www.last.fm/music/Snap%21',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]}]}

In [23]:
info_limpia = []

In [24]:
for elemento in datos_artista:
    
    if "artist" not in elemento:
        continue
    
    artista = elemento["artist"]
    
    info_limpia.append({
        "artist_name": artista.get("name"),
        "bio_summary": artista.get("bio", {}).get("summary"),
        "listeners": artista.get("stats", {}).get("listeners"),
        "playcount": artista.get("stats", {}).get("playcount"),
        "similar_artists": artista.get("similar", {}).get("artist")
    })

In [25]:
info_limpia

[{'artist_name': '2 In A Room',
  'bio_summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits) <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>',
  'listeners': '29985',
  'playcount': '117726',
  'similar_artists': [{'name': '49ers',
    'url': 'https://www.last.fm/music/49ers',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Black Box',
    'url': 'https://www.last.fm/music/Black+Box',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Technotronic',
    'url': 'https://www.last.fm/music/Technotronic',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Adamski',
    'url': 'https://www.last.fm/music/Adamski',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Snap!',
    'url': 'https://www.last.fm/music/Snap%21',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]}]},
 {'artist_name': '2001:Canarias',
  'bio_summary': ' <a href="https://www.last.fm/music/+noredirect/2001:Canarias">Read more on Last.fm</a>',
  'listeners': '267',
  'playcount': '879',
  'similar_artists': []},
 {'artist_name': 'B.P.M. System',
  'bio_summary': ' <a href="https://www.last.fm/music/B.P.M.+System">Read more on Last.fm</a>',
  'listeners': '1414',
  'playcount': '6773',
  'similar_artists': [{'name': 'Lady Gee',
    'url': 'https://www.last.fm/music/Lady+Gee',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Kike Boy',
    'url': 'https://www.last.fm/music/Kike+Boy',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Kryss',
    'url': 'https://www.last.fm/music/Kryss',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'New Limit',
    'url': 'https://www.last.fm/music/New+Limit',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Interfront',
    'url': 'https://www.last.fm/music/Interfront',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]}]},
 {'artist_name': 'Brian Cross',
  'bio_summary': 'Brian Cross is a Spanish DJ, Producer and Business Entrepreneur with a unique approach to the ever-changing music industry. With Festivals like Tomorrowland, Tomorrowworld and Sunburn GOA in his touring schedule, Sony Music as record label  and a big studio album on the way, it\'s safe to say that Brian Cross is a name to keep a close eye on in the nearest future.\n\nBorn and raised in Barcelona, Brian started his musical career remixing Frank Trax’s <a href="https://www.last.fm/music/Brian+Cross">Read more on Last.fm</a>',
  'listeners': '29255',
  'playcount': '126016',
  'similar_artists': [{'name': 'DJ Nano',
    'url': 'https://www.last.fm/music/DJ+Nano',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Dani Moreno',
    'url': 'https://www.last.fm/music/Dani+Moreno',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Jose AM',
    'url': 'https://www.last.fm/music/Jose+AM',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Wally Lopez',
    'url': 'https://www.last.fm/music/Wally+Lopez',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Geo Da Silva & Saftik',
    'url': 'https://www.last.fm/music/Geo+Da+Silva+&+Saftik',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]}]},
 {'artist_name': 'Corban Urban',
  'bio_summary': ' <a href="https://www.last.fm/music/Corban+Urban">Read more on Last.fm</a>',
  'listeners': '18',
  'playcount': '98',
  'similar_artists': []},
 {'artist_name': 'Crossfire',
  'bio_summary': 'There are at least 17 bands that have used the name Crossfire.\n\n01. A metal band from Belgium\n02. A metal band from Ankara, Turkey\n03. Drum and Bass DJ from Europe\n04. A jazz fusion band from Australia\n05. A blues band from Northern Ireland\n06. A metal band from Ecuador\n07. A glam metal band from Israel\n08. A punk/ska band from Scotland\n09. A straight edge punk band from the United Kingdom\n10. An Alternative/Punk Rock band from the UK\n11. A psychobilly/punkabilly band from Japan. <a href="https://www.last.fm/music/Crossfire">Read more on Last.fm</a>',
  'listeners': '49919',
  'playcount': '382695',
  'similar_artists': [{'name': 'Atomkraft',
    'url': 'https://www.last.fm/music/Atomkraft',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Abattoir',
    'url': 'https://www.last.fm/music/Abattoir',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Iron Angel',
    'url': 'https://www.last.fm/music/Iron+Angel',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Agent Steel',
    'url': 'https://www.last.fm/music/Agent+Steel',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Ostrogoth',
    'url': 'https://www.last.fm/music/Ostrogoth',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]}]},
 {'artist_name': 'Don Latino',
  'bio_summary': ' <a href="https://www.last.fm/music/Don+Latino">Read more on Last.fm</a>',
  'listeners': '3124',
  'playcount': '10127',
  'similar_artists': [{'name': 'Croni-K',
    'url': 'https://www.last.fm/music/Croni-K',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},

In [26]:
for artista in info_limpia:
    # extraer solo los nombres de los similares
    nombres_similares = [s['name'] for s in artista.get('similar_artists', [])]
    
    # reemplazar la lista original por solo los nombres
    artista['similar_artists'] = nombres_similares

In [27]:
info_limpia

[{'artist_name': '2 In A Room',
  'bio_summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single.\n\n"El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits) <a href="https://www.last.fm/music/2+In+A+Room">Read more on Last.fm</a>',
  'listeners': '29985',
  'playcount': '117726',
  'similar_artists': ['49ers',
   'Black Box',
   'Technotronic',
   'Adamski',
   'Snap!']},
 {'artist_name': '2001:Canarias',
  'bio_summary': ' <a href="https://www.last.fm/music/+noredirect/2001:Canarias">Read more on Last.fm</a>',
  'listeners': '267',
  'playcount': '879',
  'similar_artists': []},
 {'artist_name': 'B.P.M. System',
  'bio_summary': ' <a href="https://www.last.fm/music/B.P.M.+System">Read more on Last.fm</a>',
  'listeners': '1414',
  'playcount': '6773',
  'similar_artists': ['Lady Gee',
   'Kike Boy',
   'Kryss',
   'New Limit',
   'Interfront']},
 {'artist_name': 'Brian Cross',
  'bio_summary': 'Brian Cross is a Spanish DJ, Producer and Business Entrepreneur with a unique approach to the ever-changing music industry. With Festivals like Tomorrowland, Tomorrowworld and Sunburn GOA in his touring schedule, Sony Music as record label  and a big studio album on the way, it\'s safe to say that Brian Cross is a name to keep a close eye on in the nearest future.\n\nBorn and raised in Barcelona, Brian started his musical career remixing Frank Trax’s <a href="https://www.last.fm/music/Brian+Cross">Read more on Last.fm</a>',
  'listeners': '29255',
  'playcount': '126016',
  'similar_artists': ['DJ Nano',
   'Dani Moreno',
   'Jose AM',
   'Wally Lopez',
   'Geo Da Silva & Saftik']},
 {'artist_name': 'Corban Urban',
  'bio_summary': ' <a href="https://www.last.fm/music/Corban+Urban">Read more on Last.fm</a>',
  'listeners': '18',
  'playcount': '98',
  'similar_artists': []},
 {'artist_name': 'Crossfire',
  'bio_summary': 'There are at least 17 bands that have used the name Crossfire.\n\n01. A metal band from Belgium\n02. A metal band from Ankara, Turkey\n03. Drum and Bass DJ from Europe\n04. A jazz fusion band from Australia\n05. A blues band from Northern Ireland\n06. A metal band from Ecuador\n07. A glam metal band from Israel\n08. A punk/ska band from Scotland\n09. A straight edge punk band from the United Kingdom\n10. An Alternative/Punk Rock band from the UK\n11. A psychobilly/punkabilly band from Japan. <a href="https://www.last.fm/music/Crossfire">Read more on Last.fm</a>',
  'listeners': '49919',
  'playcount': '382695',
  'similar_artists': ['Atomkraft',
   'Abattoir',
   'Iron Angel',
   'Agent Steel',
   'Ostrogoth']},
 {'artist_name': 'Don Latino',
  'bio_summary': ' <a href="https://www.last.fm/music/Don+Latino">Read more on Last.fm</a>',
  'listeners': '3124',
  'playcount': '10127',
  'similar_artists': ['Croni-K',
   'Fraag Malas',
   'Yulien Oviedo',
   'Jay Santos',
   'Gocho']},
 {'artist_name': 'Fiesta pop',
  'bio_summary': ' <a href="https://www.last.fm/music/Fiesta+pop">Read more on Last.fm</a>',
  'listeners': '1032',
  'playcount': '4664',
  'similar_artists': ['The Refrescos',
   'Los Inhumanos',
   'Alarma',
   'Los Rebeldes',
   'David Otero']},
 {'artist_name': 'Freeway',
  'bio_summary': 'There is more than one artist with the name Freeway:\n\nThe first is:\n\n1. Leslie Edward Pridgen (born March 24, 1977), better known by his stage name Freeway, is an American rapper. Freeway a.k.a. Philly Freeway began rapping while in high school. He later met fellow rapper Beanie Sigel, who would be signed to Roc-A-Fella and later help Freeway get a contract with the record label. Freeway became one of the label\'s most visible artists after making <a href="https://www.last.fm/music/Freeway">Read more on Last.fm</a>',
  'listeners': '333342',
  'playcount': '2276155',
  'similar_artists': ['Memphis Bleek',
   'Beanie Sigel',
   "Cam'ron",
   'Jadakiss',
   'Juelz Santana']},
 {'artist_name': 'Generis',
  'bio_summary': ' <a href="https://www.last.fm/music/Generis">Read more on Last.fm</a>',
  'listeners': '541',
  'playcount': '1882',
  'similar_artists': ['New Limit',
   'Aldus Haza',
   'Committe',
   'Kike Boy',
   'Emotional G']},
 {'artist_name': 'Hanson',
  'bio_summary': 'There are at least two artists which have used the name Hanson\n1. A pop rock group from Oklahoma, United States\n2. A funk rock group from the United Kingdom active in the 1970\'s.\n\n1. Hanson are an American pop rock band from Tulsa, Oklahoma. The band consists of guitarist and vocalist Isaac Hanson (born November 17, 1980) pianist and vocalist Taylor Hanson (born March 14, 1983), and drummer and vocalist Zac Hanson (born October 22, 1985). Their work has spanned many different genres, including rock, blues, folk, and pop. <a href="https://www.last.fm/music/Hanson">Read more on Last.fm</a>',
  'listeners': '989746',
  'playcount': '14882560',
  'similar_artists': ['Aaron Carter',
   'Backstreet Boys',
   'O-Town',
   'Nick Carter',
   '98 Degrees']},
 {'artist_name': 'High Density',
  'bio_summary': ' <a href="https://www.last.fm/music/High+Density">Read more on Last.fm</a>',
  'listeners': '644',
  'playcount': '2826',
  'similar_artists': ['Nacho Division',
   'Aldus Haza',
   'K.R.B.',
   'PG2',
   'Vatios']},
 {'artist_name': 'Iggy Pop',
  'bio_summary': '\nIggy Pop (born James Newell Osterberg, Jr.; April 21, 1947) is an American singer, songwriter, musician, and actor. Though widely known as an innovator and "godfather" of punk rock, Pop\'s music has encompassed a number of styles over the years, including pop, hard rock, jazz and blues. Pop became known as \'Iggy\' in high school, during which time he served as drummer for local blues band The Iguanas. He is vocalist of influential proto-punk band The Stooges (Pop and the other surviving members of the group reunited in 2003) <a href="https://www.last.fm/music/Iggy+Pop">Read more on Last.fm</a>',
  'listeners': '2240890',
  'playcount': '44334925',
  'similar_artists': ['The Stooges',
   'Iggy Pop & James Williamson',
   'Lou Reed',
   'David Bowie',
   'Patti Smith']},
 {'artist_name': 'Jerry Daley',
  'bio_summary': 'Jerry Daley is a Spanish dance project produced by J.V. Mollá.\nSingles: «Gold», «Living On My Own», «Send Me An Angel», «This Is Not America» and «Love Kills».  <a href="https://www.last.fm/music/Jerry+Daley">Read more on Last.fm</a>',
  'listeners': '1781',
  'playcount': '5987',
  'similar_artists': ['Sensity World',
   'New Limit',
   'Piropo',
   'Kryss',
   'ACTV']},
 {'artist_name': 'Just Blaze',
  'bio_summary': 'Justin Smith (born in Paterson, New Jersey), better known as Just Blaze, is an American hip hop music producer. Just Blaze has produced tracks for The Beastie Boys, Jay-Z, Usher, Kanye West, Busta Rhymes, Jadakiss, Memphis Bleek, Beanie Sigel, The Game, DMX, T.I., Fat Joe, Rhymefest, Ghostface Killah, MED, Fabolous and Joe Budden. He also recorded several tracks for the popular video games Tiger Woods PGA Tour 2004 and NBA STREET VOL. 2 and is a playable character in the game as well. <a href="https://www.last.fm/music/Just+Blaze">Read more on Last.fm</a>',
  'listeners': '23793',
  'playcount': '120090',
  'similar_artists': ['Ski Beatz',
   'Khrysis',
   'Nottz',
   'Kidz in the Hall',
   'Johnson&Jonson']},
 {'artist_name': 'Kamembert',
  'bio_summary': ' <a href="https://www.last.fm/music/Kamembert">Read more on Last.fm</a>',
  'listeners': '374',
  'playcount': '1338',
  'similar_artists': ['Brighton 64',
   'kamenbert',
   'Los Negativos',
   'Los Elegantes',
   'Kristallin & Michele Bernard']},
 {'artist_name': 'Kike Boy',
  'bio_summary': 'Enrique Pascual López Mejía also known as Kike Boy is a Spanish deejay and producer, who released a lot of hits in the 90s.\nSingles: "Orbital", "Croack", "Generation X", "Kabuki", "Farmatron", "Teknogroove", "Jumper", "I\'m The Creator", "Trouble Shooting" and "In The Beginning". <a href="https://www.last.fm/music/Kike+Boy">Read more on Last.fm</a>',
  'listeners': '1607',
  'playcount': '5877',
  'similar_artists': ['B.P.M. System',
   'Sensity World',
   'Piropo',
   'New Limit',
   'ACTV']},
 {'artist_name': 'Korpus',
  'bio_summary': 'Korpus is a death/thrash metal band from Dresden, Germany formed in 2008.\n\nhttp://www.korpus-metal.de <a href="https://www.last.fm/music/Korpus">Read more on Last.fm</a>',
  'listeners': '2315',
  'playcount': '14113',
  'similar_artists': ['Super Box',
   'Azzaron',
   'Grzegorz Kupczyk',
   'Open Fire',
   'Lord Vader']},
 {'artist_name': 'Kriss',
  'bio_summary': ' <a href="https://www.last.fm/music/Kriss">Read more on Last.fm</a>',
  'listeners': '8178',
  'playcount': '114683',
  'similar_artists': ['Kriss Cologne',
   'Burger',
   'Spieltrieb',
   'Strom & Wasser',
   'Unkraut Liedermacher']},
 {'artist_name': 'Kryss',
  'bio_summary': 'There are different artists sharing the same name:\n\n1. Atmospheric Black Metal band from Leipzig, Germany.\n2. Cristina Orue Echevarria (aka Kryss or Kriss), Spanish dance-music singer. <a href="https://www.last.fm/music/Kryss">Read more on Last.fm</a>',
  'listeners': '2126',
  'playcount': '7624',
  'similar_artists': ['New Limit',
   'Sensity World',
   'DJ Sylvan',
   'Piropo',
   'Jerry Daley']},
 {'artist_name': 'Los Flechazos',
  'bio_summary': ' <a href="https://www.last.fm/music/Los+Flechazos">Read more on Last.fm</a>',
  'listeners': '16779',
  'playcount': '191557',
  'similar_artists': ['Cooper',
   'Brighton 64',
   'la granja',
   'La Costa Brava',
   "Surfin' Bichos"]},
 {'artist_name': 'McFly',
  'bio_summary': 'McFly are a British pop rock band who first found fame in 2003. The band, formed in London, was founded by Tom Fletcher (lead vocals/guitar/piano) and also consists of Danny Jones (lead vocals/guitar), Dougie Poynter (vocals/bass guitar) and Harry Judd (drums). They have released seven studio albums (their 2004 debut "Room on the 3rd Floor", 2005\'s "Wonderland", 2006\'s "Motion in the Ocean", 2008\'s "Radio:ACTIVE", 2010\'s "Above the Noise", 2020\'s "Young Dumb Thrills", and 2023\'s "Power to Play") and had seven #1 singles. <a href="https://www.last.fm/music/McFly">Read more on Last.fm</a>',
  'listeners': '798766',
  'playcount': '47118122',
  'similar_artists': ['McBusted',
   'Busted',
   'Jonas Brothers',
   'Scouting for Girls',
   'The Vamps']},
 {'artist_name': 'Megabass',
  'bio_summary': 'MegaBass consists of Darren Ash and Martin Smith. They have released various mixed albums, most notably 3 megaBass albums and 3 Hit The Decks albums. Music varies from Dance, Latin Freestyle & R&B (Megabass series) to Jungle & New Beat (Hit The Decks 3). <a href="https://www.last.fm/music/Megabass">Read more on Last.fm</a>',
  'listeners': '705',
  'playcount': '4194',
  'similar_artists': ['Two Little Boys',
   'Nacho Division',
   'High Density',
   "Smart E's",
   'The Hypnotist']},
 {'artist_name': 'Memphis Bleek',
  'bio_summary': 'Malik Thuston Cox (born on June 23, 1978) better known as Memphis Bleek, is a Brooklyn rapper who made his first appearance in Hip Hop on Jay-Z\'s debut album, Reasonable Doubt in 1996. Memphis Bleek regularly came in contact with rap legends such as The Notorious B.I.G. and Jay-Z during his childhood, and has collaborated with artists such as Beanie Sigel, Ja Rule and Missy Elliott, among others. "Memphis" is an acronym for Making Easy Money Pimping Hoes In Style. <a href="https://www.last.fm/music/Memphis+Bleek">Read more on Last.fm</a>',
  'listeners': '325444',
  'playcount': '1883926',
  'similar_artists': ['Freeway',
   'Beanie Sigel',
   'Jadakiss',
   "Cam'ron",
   'Juelz Santana']},
 {'artist_name': 'Midiland',
  'bio_summary': ' <a href="https://www.last.fm/music/Midiland">Read more on Last.fm</a>',
  'listeners': '61',
  'playcount': '227',
  'similar_artists': ['EI8HT a\xa0Offset',
   'René de Wael',
   'Mark Sandell & Neil Watson',
   'Mighty Monster',
   'Masego a\xa0Don Toliver']},
 {'artist_name': 'Omega',
  'bio_summary': 'The are multiple artists called Omega:\n1. A Hungarian progressive and hard rock band\n2. An alias of techno musician Naoki\n3. A Lithuanian pop group\n4. An American rapper\n5. A dubstep artist\n6. A British metal band\n7. A Greek black/thrash/speed metal band\n8. A Dominican mambo singer\n9. A Chilean rapper\n10. An Italian black/avantgarde/ambient metal band\n11. A Beat rock ensemble from Estonia\n\n1. Omega is one of the most successful Hungarian rock bands. <a href="https://www.last.fm/music/Omega">Read more on Last.fm</a>',
  'listeners': '326403',
  'playcount': '3666355',
  'similar_artists': ['Ken Hensley',
   'Uriah Heep',
   'Czesław Niemen',
   "Manfred Mann's Earth Band",
   'SBB']},
 {'artist_name': 'Peter Polycarpou',
  'bio_summary': ' <a href="https://www.last.fm/music/Peter+Polycarpou">Read more on Last.fm</a>',
  'listeners': '4409',
  'playcount': '22875',
  'similar_artists': ['Original London Cast',
   'Roger Allam',
   'Gavin Creel',
   'Brent Carver',
   'Les Misérables: International Cast']},
 {'artist_name': 'Squeeze',
  'bio_summary': 'Squeeze are an English pop rock band  formed in London, England in 1974. The band was formed by songwriters Glenn Tilbrook (vocals, guitar) and Chris Difford (guitar, vocals) who have been the group\'s only constant members since the band\'s formation (with the exception of Difford\'s hiatus from the band in 1999). Aside from Difford and Tilbrook, the band currently consists of Stephen Large (keyboards), Lucy Shaw (bass) and Simon Hanson (drums).\n\nThe group initially split in 1982, but reunited in 1985 until splitting once more in 1999. <a href="https://www.last.fm/music/Squeeze">Read more on Last.fm</a>',
  'listeners': '711135',
  'playcount': '9354506',
  'similar_artists': ['Elvis Costello & The Attractions',
   'Elvis Costello',
   'Joe Jackson',
   'Marshall Crenshaw',
   'Nick Lowe']},
 {'artist_name': 'Tess',
  'bio_summary': 'There are currently 5 acts listed under the solo/band name TESS.\n\n(1) Tess is a French metal\\hardcore band.\n(2) Tess is a band from Memphis, TN featuring members of Neev, Blesser, and Niur.\n(3) Tess is a  Swedish eurodance artist  .\n(4) Tess were a female Spanish pop band.\n(5) Tess Gaerthé , known as Tess is a young singer from the Netherlands.\n(6) TESS is a male singer songrwiter from the UK. His song "Save me from myself" is currently featured on last. <a href="https://www.last.fm/music/Tess">Read more on Last.fm</a>',
  'listeners': '68882',
  'playcount': '474437',
  'similar_artists': ['Adept',
   'A Static Lullaby',
   'Eyes Set to Kill',
   'Envy',
   'Funeral For A Friend']},
 {'artist_name': 'The Nativos',
  'bio_summary': ' <a href="https://www.last.fm/music/The+Nativos">Read more on Last.fm</a>',
  'listeners': '370',
  'playcount': '1282',
  'similar_artists': ['Pistones',
   'Glutamato Ye-Ye',
   'La Dama Se Esconde',
   'Rey Lui',
   'La Coartada']},
 {'artist_name': 'The Style Council',
  'bio_summary': 'The Style Council were an English musical group formed in 1983 by ex-The Jam singer and guitarist Paul Weller with keyboardist Mick Talbot. The permanent lineup grew to include drummer Steve White and Weller\'s then-wife, vocalist Dee C. Lee. Other artists such as Tracie Young and Tracey Thorn (Everything but the Girl) also collaborated with the group.\n\nThe band showed a diversity of musical styles. Singles "Speak Like a Child" (with its loud soul-influenced style) <a href="https://www.last.fm/music/The+Style+Council">Read more on Last.fm</a>',
  'listeners': '407561',
  'playcount': '5980455',
  'similar_artists': ['The Jam',
   'Paul Weller',
   'Aztec Camera',
   'The Blow Monkeys',
   'Prefab Sprout']}]

In [28]:
for artista in info_limpia:
    bio = artista.get("bio_summary")

    if bio:
        bio = bio.split("<a href=")[0]
        bio = bio.replace("Read more on Last.fm", "")
        bio = bio.replace("\n", " ")
        bio = " ".join(bio.split())

        if not bio.strip():
            bio = None

    artista["bio_summary"] = bio

In [29]:
info_limpia

[{'artist_name': '2 In A Room',
  'bio_summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single. "El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits)',
  'listeners': '29985',
  'playcount': '117726',
  'similar_artists': ['49ers',
   'Black Box',
   'Technotronic',
   'Adamski',
   'Snap!']},
 {'artist_name': '2001:Canarias',
  'bio_summary': None,
  'listeners': '267',
  'playcount': '879',
  'similar_artists': []},
 {'artist_name': 'B.P.M. System',
  'bio_summary': None,
  'listeners': '1414',
  'playcount': '6773',
  'similar_artists': ['Lady Gee',
   'Kike Boy',
   'Kryss',
   'New Limit',
   'Interfront']},
 {'artist_name': 'Brian Cross',
  'bio_summary': "Brian Cross is a Spanish DJ, Producer and Business Entrepreneur with a unique approach to the ever-changing music industry. With Festivals like Tomorrowland, Tomorrowworld and Sunburn GOA in his touring schedule, Sony Music as record label and a big studio album on the way, it's safe to say that Brian Cross is a name to keep a close eye on in the nearest future. Born and raised in Barcelona, Brian started his musical career remixing Frank Trax’s",
  'listeners': '29255',
  'playcount': '126016',
  'similar_artists': ['DJ Nano',
   'Dani Moreno',
   'Jose AM',
   'Wally Lopez',
   'Geo Da Silva & Saftik']},
 {'artist_name': 'Corban Urban',
  'bio_summary': None,
  'listeners': '18',
  'playcount': '98',
  'similar_artists': []},
 {'artist_name': 'Crossfire',
  'bio_summary': 'There are at least 17 bands that have used the name Crossfire. 01. A metal band from Belgium 02. A metal band from Ankara, Turkey 03. Drum and Bass DJ from Europe 04. A jazz fusion band from Australia 05. A blues band from Northern Ireland 06. A metal band from Ecuador 07. A glam metal band from Israel 08. A punk/ska band from Scotland 09. A straight edge punk band from the United Kingdom 10. An Alternative/Punk Rock band from the UK 11. A psychobilly/punkabilly band from Japan.',
  'listeners': '49919',
  'playcount': '382695',
  'similar_artists': ['Atomkraft',
   'Abattoir',
   'Iron Angel',
   'Agent Steel',
   'Ostrogoth']},
 {'artist_name': 'Don Latino',
  'bio_summary': None,
  'listeners': '3124',
  'playcount': '10127',
  'similar_artists': ['Croni-K',
   'Fraag Malas',
   'Yulien Oviedo',
   'Jay Santos',
   'Gocho']},
 {'artist_name': 'Fiesta pop',
  'bio_summary': None,
  'listeners': '1032',
  'playcount': '4664',
  'similar_artists': ['The Refrescos',
   'Los Inhumanos',
   'Alarma',
   'Los Rebeldes',
   'David Otero']},
 {'artist_name': 'Freeway',
  'bio_summary': "There is more than one artist with the name Freeway: The first is: 1. Leslie Edward Pridgen (born March 24, 1977), better known by his stage name Freeway, is an American rapper. Freeway a.k.a. Philly Freeway began rapping while in high school. He later met fellow rapper Beanie Sigel, who would be signed to Roc-A-Fella and later help Freeway get a contract with the record label. Freeway became one of the label's most visible artists after making",
  'listeners': '333342',
  'playcount': '2276155',
  'similar_artists': ['Memphis Bleek',
   'Beanie Sigel',
   "Cam'ron",
   'Jadakiss',
   'Juelz Santana']},
 {'artist_name': 'Generis',
  'bio_summary': None,
  'listeners': '541',
  'playcount': '1882',
  'similar_artists': ['New Limit',
   'Aldus Haza',
   'Committe',
   'Kike Boy',
   'Emotional G']},
 {'artist_name': 'Hanson',
  'bio_summary': "There are at least two artists which have used the name Hanson 1. A pop rock group from Oklahoma, United States 2. A funk rock group from the United Kingdom active in the 1970's. 1. Hanson are an American pop rock band from Tulsa, Oklahoma. The band consists of guitarist and vocalist Isaac Hanson (born November 17, 1980) pianist and vocalist Taylor Hanson (born March 14, 1983), and drummer and vocalist Zac Hanson (born October 22, 1985). Their work has spanned many different genres, including rock, blues, folk, and pop.",
  'listeners': '989746',
  'playcount': '14882560',
  'similar_artists': ['Aaron Carter',
   'Backstreet Boys',
   'O-Town',
   'Nick Carter',
   '98 Degrees']},
 {'artist_name': 'High Density',
  'bio_summary': None,
  'listeners': '644',
  'playcount': '2826',
  'similar_artists': ['Nacho Division',
   'Aldus Haza',
   'K.R.B.',
   'PG2',
   'Vatios']},
 {'artist_name': 'Iggy Pop',
  'bio_summary': 'Iggy Pop (born James Newell Osterberg, Jr.; April 21, 1947) is an American singer, songwriter, musician, and actor. Though widely known as an innovator and "godfather" of punk rock, Pop\'s music has encompassed a number of styles over the years, including pop, hard rock, jazz and blues. Pop became known as \'Iggy\' in high school, during which time he served as drummer for local blues band The Iguanas. He is vocalist of influential proto-punk band The Stooges (Pop and the other surviving members of the group reunited in 2003)',
  'listeners': '2240890',
  'playcount': '44334925',
  'similar_artists': ['The Stooges',
   'Iggy Pop & James Williamson',
   'Lou Reed',
   'David Bowie',
   'Patti Smith']},
 {'artist_name': 'Jerry Daley',
  'bio_summary': 'Jerry Daley is a Spanish dance project produced by J.V. Mollá. Singles: «Gold», «Living On My Own», «Send Me An Angel», «This Is Not America» and «Love Kills».',
  'listeners': '1781',
  'playcount': '5987',
  'similar_artists': ['Sensity World',
   'New Limit',
   'Piropo',
   'Kryss',
   'ACTV']},
 {'artist_name': 'Just Blaze',
  'bio_summary': 'Justin Smith (born in Paterson, New Jersey), better known as Just Blaze, is an American hip hop music producer. Just Blaze has produced tracks for The Beastie Boys, Jay-Z, Usher, Kanye West, Busta Rhymes, Jadakiss, Memphis Bleek, Beanie Sigel, The Game, DMX, T.I., Fat Joe, Rhymefest, Ghostface Killah, MED, Fabolous and Joe Budden. He also recorded several tracks for the popular video games Tiger Woods PGA Tour 2004 and NBA STREET VOL. 2 and is a playable character in the game as well.',
  'listeners': '23793',
  'playcount': '120090',
  'similar_artists': ['Ski Beatz',
   'Khrysis',
   'Nottz',
   'Kidz in the Hall',
   'Johnson&Jonson']},
 {'artist_name': 'Kamembert',
  'bio_summary': None,
  'listeners': '374',
  'playcount': '1338',
  'similar_artists': ['Brighton 64',
   'kamenbert',
   'Los Negativos',
   'Los Elegantes',
   'Kristallin & Michele Bernard']},
 {'artist_name': 'Kike Boy',
  'bio_summary': 'Enrique Pascual López Mejía also known as Kike Boy is a Spanish deejay and producer, who released a lot of hits in the 90s. Singles: "Orbital", "Croack", "Generation X", "Kabuki", "Farmatron", "Teknogroove", "Jumper", "I\'m The Creator", "Trouble Shooting" and "In The Beginning".',
  'listeners': '1607',
  'playcount': '5877',
  'similar_artists': ['B.P.M. System',
   'Sensity World',
   'Piropo',
   'New Limit',
   'ACTV']},
 {'artist_name': 'Korpus',
  'bio_summary': 'Korpus is a death/thrash metal band from Dresden, Germany formed in 2008. http://www.korpus-metal.de',
  'listeners': '2315',
  'playcount': '14113',
  'similar_artists': ['Super Box',
   'Azzaron',
   'Grzegorz Kupczyk',
   'Open Fire',
   'Lord Vader']},
 {'artist_name': 'Kriss',
  'bio_summary': None,
  'listeners': '8178',
  'playcount': '114683',
  'similar_artists': ['Kriss Cologne',
   'Burger',
   'Spieltrieb',
   'Strom & Wasser',
   'Unkraut Liedermacher']},
 {'artist_name': 'Kryss',
  'bio_summary': 'There are different artists sharing the same name: 1. Atmospheric Black Metal band from Leipzig, Germany. 2. Cristina Orue Echevarria (aka Kryss or Kriss), Spanish dance-music singer.',
  'listeners': '2126',
  'playcount': '7624',
  'similar_artists': ['New Limit',
   'Sensity World',
   'DJ Sylvan',
   'Piropo',
   'Jerry Daley']},
 {'artist_name': 'Los Flechazos',
  'bio_summary': None,
  'listeners': '16779',
  'playcount': '191557',
  'similar_artists': ['Cooper',
   'Brighton 64',
   'la granja',
   'La Costa Brava',
   "Surfin' Bichos"]},
 {'artist_name': 'McFly',
  'bio_summary': 'McFly are a British pop rock band who first found fame in 2003. The band, formed in London, was founded by Tom Fletcher (lead vocals/guitar/piano) and also consists of Danny Jones (lead vocals/guitar), Dougie Poynter (vocals/bass guitar) and Harry Judd (drums). They have released seven studio albums (their 2004 debut "Room on the 3rd Floor", 2005\'s "Wonderland", 2006\'s "Motion in the Ocean", 2008\'s "Radio:ACTIVE", 2010\'s "Above the Noise", 2020\'s "Young Dumb Thrills", and 2023\'s "Power to Play") and had seven #1 singles.',
  'listeners': '798766',
  'playcount': '47118122',
  'similar_artists': ['McBusted',
   'Busted',
   'Jonas Brothers',
   'Scouting for Girls',
   'The Vamps']},
 {'artist_name': 'Megabass',
  'bio_summary': 'MegaBass consists of Darren Ash and Martin Smith. They have released various mixed albums, most notably 3 megaBass albums and 3 Hit The Decks albums. Music varies from Dance, Latin Freestyle & R&B (Megabass series) to Jungle & New Beat (Hit The Decks 3).',
  'listeners': '705',
  'playcount': '4194',
  'similar_artists': ['Two Little Boys',
   'Nacho Division',
   'High Density',
   "Smart E's",
   'The Hypnotist']},
 {'artist_name': 'Memphis Bleek',
  'bio_summary': 'Malik Thuston Cox (born on June 23, 1978) better known as Memphis Bleek, is a Brooklyn rapper who made his first appearance in Hip Hop on Jay-Z\'s debut album, Reasonable Doubt in 1996. Memphis Bleek regularly came in contact with rap legends such as The Notorious B.I.G. and Jay-Z during his childhood, and has collaborated with artists such as Beanie Sigel, Ja Rule and Missy Elliott, among others. "Memphis" is an acronym for Making Easy Money Pimping Hoes In Style.',
  'listeners': '325444',
  'playcount': '1883926',
  'similar_artists': ['Freeway',
   'Beanie Sigel',
   'Jadakiss',
   "Cam'ron",
   'Juelz Santana']},
 {'artist_name': 'Midiland',
  'bio_summary': None,
  'listeners': '61',
  'playcount': '227',
  'similar_artists': ['EI8HT a\xa0Offset',
   'René de Wael',
   'Mark Sandell & Neil Watson',
   'Mighty Monster',
   'Masego a\xa0Don Toliver']},
 {'artist_name': 'Omega',
  'bio_summary': 'The are multiple artists called Omega: 1. A Hungarian progressive and hard rock band 2. An alias of techno musician Naoki 3. A Lithuanian pop group 4. An American rapper 5. A dubstep artist 6. A British metal band 7. A Greek black/thrash/speed metal band 8. A Dominican mambo singer 9. A Chilean rapper 10. An Italian black/avantgarde/ambient metal band 11. A Beat rock ensemble from Estonia 1. Omega is one of the most successful Hungarian rock bands.',
  'listeners': '326403',
  'playcount': '3666355',
  'similar_artists': ['Ken Hensley',
   'Uriah Heep',
   'Czesław Niemen',
   "Manfred Mann's Earth Band",
   'SBB']},
 {'artist_name': 'Peter Polycarpou',
  'bio_summary': None,
  'listeners': '4409',
  'playcount': '22875',
  'similar_artists': ['Original London Cast',
   'Roger Allam',
   'Gavin Creel',
   'Brent Carver',
   'Les Misérables: International Cast']},
 {'artist_name': 'Squeeze',
  'bio_summary': "Squeeze are an English pop rock band formed in London, England in 1974. The band was formed by songwriters Glenn Tilbrook (vocals, guitar) and Chris Difford (guitar, vocals) who have been the group's only constant members since the band's formation (with the exception of Difford's hiatus from the band in 1999). Aside from Difford and Tilbrook, the band currently consists of Stephen Large (keyboards), Lucy Shaw (bass) and Simon Hanson (drums). The group initially split in 1982, but reunited in 1985 until splitting once more in 1999.",
  'listeners': '711135',
  'playcount': '9354506',
  'similar_artists': ['Elvis Costello & The Attractions',
   'Elvis Costello',
   'Joe Jackson',
   'Marshall Crenshaw',
   'Nick Lowe']},
 {'artist_name': 'Tess',
  'bio_summary': 'There are currently 5 acts listed under the solo/band name TESS. (1) Tess is a French metal\\hardcore band. (2) Tess is a band from Memphis, TN featuring members of Neev, Blesser, and Niur. (3) Tess is a Swedish eurodance artist . (4) Tess were a female Spanish pop band. (5) Tess Gaerthé , known as Tess is a young singer from the Netherlands. (6) TESS is a male singer songrwiter from the UK. His song "Save me from myself" is currently featured on last.',
  'listeners': '68882',
  'playcount': '474437',
  'similar_artists': ['Adept',
   'A Static Lullaby',
   'Eyes Set to Kill',
   'Envy',
   'Funeral For A Friend']},
 {'artist_name': 'The Nativos',
  'bio_summary': None,
  'listeners': '370',
  'playcount': '1282',
  'similar_artists': ['Pistones',
   'Glutamato Ye-Ye',
   'La Dama Se Esconde',
   'Rey Lui',
   'La Coartada']},
 {'artist_name': 'The Style Council',
  'bio_summary': 'The Style Council were an English musical group formed in 1983 by ex-The Jam singer and guitarist Paul Weller with keyboardist Mick Talbot. The permanent lineup grew to include drummer Steve White and Weller\'s then-wife, vocalist Dee C. Lee. Other artists such as Tracie Young and Tracey Thorn (Everything but the Girl) also collaborated with the group. The band showed a diversity of musical styles. Singles "Speak Like a Child" (with its loud soul-influenced style)',
  'listeners': '407561',
  'playcount': '5980455',
  'similar_artists': ['The Jam',
   'Paul Weller',
   'Aztec Camera',
   'The Blow Monkeys',
   'Prefab Sprout']}]

In [30]:
for artista in info_limpia:
    artista["listeners"] = int(artista["listeners"]) if artista["listeners"] else 0
    artista["playcount"] = int(artista["playcount"]) if artista["playcount"] else 0

In [31]:
info_limpia[:1]

[{'artist_name': '2 In A Room',
  'bio_summary': '2 In A Room is a hip hop and house music duo from Washington Heights, New York, which includes rapper Rafael "Dose" Vargas and producer/remixer Roger "Rog Nice" Pauletta. They are best known for their 1990 hit "Wiggle It", which spent two weeks at #1 on the Hot Dance Music/Club Play chart (#3 in the UK) and then crossed over to mainstream radio and climbed to #15 on the Hot 100, eventually becoming a gold single. "El Trago (the Drink)" was a #86 Hot 100 chart entry (the last of their pop hits)',
  'listeners': 29985,
  'playcount': 117726,
  'similar_artists': ['49ers',
   'Black Box',
   'Technotronic',
   'Adamski',
   'Snap!']}]

In [36]:
df_similares = []

In [37]:
similar_data = []

In [38]:
for artista in info_limpia:
    artista_principal = artista["artist_name"]
    # si quieres solo 5 similares
    for pos, similar in enumerate(artista["similar_artists"][:5], start=1):
        similar_data.append(
            {
                "artist_name": artista_principal,
                "similar_artist_name": similar,
                "rank": pos,
            }
        )

In [39]:
df_similares = pd.DataFrame(similar_data)
df_similares = df_similares.drop_duplicates().reset_index(drop=True)

In [40]:
df_similares

           artist_name similar_artist_name  rank
0          2 In A Room               49ers     1
1          2 In A Room           Black Box     2
2          2 In A Room        Technotronic     3
3          2 In A Room             Adamski     4
4          2 In A Room               Snap!     5
..                 ...                 ...   ...
140  The Style Council             The Jam     1
141  The Style Council         Paul Weller     2
142  The Style Council        Aztec Camera     3
143  The Style Council    The Blow Monkeys     4
144  The Style Council       Prefab Sprout     5

[145 rows x 3 columns]

In [41]:
df_similares.to_csv("artista_similar_reggaeton.csv", index=False)

# TABLA COMPLETA LAST.FM

In [ ]:
df1 = pd.DataFrame(info_limpia)

In [ ]:
df1

,artist_name,bio_summary,listeners,playcount,similar_artists
0,2 In A Room,2 In A Room is a hip hop and house music duo f...,29977,117673,"[49ers, Black Box, Cappella, Technotronic, Mr...."
1,2001:Canarias,None,267,877,[]
2,B.P.M. System,None,1409,6747,"[Lady Gee, Kike Boy, Kryss, New Limit, Interfr..."
3,Brian Cross,"Brian Cross is a Spanish DJ, Producer and Busi...",29253,125998,"[DJ Nano, Dani Moreno, Jose AM, Wally Lopez, G..."
4,Corban Urban,None,18,98,[]
5,Crossfire,There are at least 17 bands that have used the...,49882,382443,"[Atomkraft, Iron Angel, Agent Steel, Acid, Aba..."
6,Don Latino,None,3123,10119,"[Croni-K, Fraag Malas, Yulien Oviedo, Jay Sant..."
7,Fiesta pop,None,1032,4664,"[The Refrescos, Los Inhumanos, David Otero, Al..."
8,Freeway,There is more than one artist with the name Fr...,333157,2274785,"[Memphis Bleek, Beanie Sigel, Jadakiss, Cam'ro..."
9,Generis,None,541,1877,"[New Limit, Aldus Haza, Kike Boy, Emotional G,..."
10,Hanson,There are at least two artists which have used...,989366,14878129,"[Aaron Carter, O-Town, Backstreet Boys, Nick C..."
11,High Density,None,644,2826,"[Nacho Division, Aldus Haza, K.R.B., PG2, Bpm ..."
12,Iggy Pop,"Iggy Pop (born James Newell Osterberg, Jr.; Ap...",2239746,44307619,"[The Stooges, Iggy Pop & James Williamson, Lou..."
13,Jerry Daley,Jerry Daley is a Spanish dance project produce...,1781,5984,"[Sensity World, New Limit, Piropo, Kryss, ACTV]"
14,Just Blaze,"Justin Smith (born in Paterson, New Jersey), b...",23785,120061,"[Ski Beatz, Khrysis, Nottz, Kidz in the Hall, ..."
15,Kamembert,None,373,1337,"[Brighton 64, kamenbert, Los Negativos, Los El..."
16,Kike Boy,Enrique Pascual López Mejía also known as Kike...,1605,5871,"[B.P.M. System, Sensity World, Piropo, New Lim..."
17,Korpus,Korpus is a death/thrash metal band from Dresd...,2298,14018,"[Super Box, Azzaron, Grzegorz Kupczyk, Open Fi..."
18,Kriss,None,8170,114626,"[Kriss Cologne, Burger, Spieltrieb, Strom & Wa..."
19,Kryss,There are different artists sharing the same n...,2121,7604,"[New Limit, Sensity World, DJ Sylvan, Piropo, ..."
20,Los Flechazos,None,16775,191525,"[Cooper, Brighton 64, la granja, La Costa Brav..."
21,McFly,McFly are a British pop rock band who first fo...,798487,47104987,"[McBusted, Busted, Scouting for Girls, Jonas B..."
22,Megabass,MegaBass consists of Darren Ash and Martin Smi...,705,4193,"[Two Little Boys, Nacho Division, The Hypnotis..."
23,Memphis Bleek,"Malik Thuston Cox (born on June 23, 1978) bett...",325293,1882826,"[Freeway, Beanie Sigel, Jadakiss, Cam'ron, Jue..."
24,Midiland,None,61,225,"[Mighty Monster, René de Wael, Mark Sandell & ..."
25,Omega,The are multiple artists called Omega: 1. A Hu...,326056,3661420,"[Ken Hensley, Uriah Heep, Czesław Niemen, Manf..."
26,Peter Polycarpou,None,4403,22852,"[Original London Cast, Roger Allam, Gavin Cree..."
27,Squeeze,Squeeze are an English pop rock band formed in...,710679,9344907,"[Elvis Costello & The Attractions, Joe Jackson..."
28,Tess,There are currently 5 acts listed under the so...,68864,474246,"[Adept, A Static Lullaby, Eyes Set to Kill, En..."
29,The Nativos,None,369,1281,"[Glutamato Ye-Ye, Pistones, Rey Lui, La Coarta..."
30,The Style Council,The Style Council were an English musical grou...,407349,5974591,"[The Jam, Paul Weller, Aztec Camera, The Blow ..."

# TABLA COMPLETA SPOTIFY

In [ ]:
df2 = pd.DataFrame(canciones_filtrada)

In [ ]:
df2

,id,artist_name,track_name,genre,year
0,1hvf4GP5GbVQ8aPbVXIsEW,McFly,McFly The Musical - Live At The Royal Albert Hall,reggaeton,2013
1,46lg4dxjDyig9MVX271szQ,McFly,McFly The Musical - Live At The Royal Albert Hall,reggaeton,2013
2,4ApSXhiRpboS6M8e0kg9Jq,Tess,The Second That You Sleep - Interphace Remix,reggaeton,2013
3,36rH4mPe87uobaXzb5uPNG,Midiland,Renegade Dancers - Version Dance,reggaeton,2013
4,1KqCw7AwVIgRJAIBgH1poL,Los Flechazos,Suzette,reggaeton,2013
5,318HbfUmnbbZ9C0wmF4Hf0,Kamembert,Sha la la,reggaeton,2013
6,5xiHRwTo3PiPjMg62oaJjL,Don Latino,Tuku Taka - Remix,reggaeton,2014
7,5xiHRwTo3PiPjMg62oaJjL,Crossfire,Tuku Taka - Remix,reggaeton,2014
8,7vHIaYACvYiyzSvP55QqU5,Corban Urban,Alabarte,reggaeton,2014
9,60khFr0gE03gfb78q5gyRW,Freeway,Let's Go,reggaeton,2014
10,60khFr0gE03gfb78q5gyRW,Memphis Bleek,Let's Go,reggaeton,2014
11,60khFr0gE03gfb78q5gyRW,Just Blaze,Let's Go,reggaeton,2014
12,0LJhox6uOMtrHtLKbZ8gLm,Peter Polycarpou,Chapter 1,reggaeton,2014
13,30OgJClocf3npT0SZIbCiy,Kryss,Tonight,reggaeton,2014
14,2yrcjgxdcMpdA8JvOLVKGl,Hanson,MMMBop,reggaeton,2014
15,072RMxyaiPGuUfop8jAemH,Kriss,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
16,072RMxyaiPGuUfop8jAemH,B.P.M. System,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
17,072RMxyaiPGuUfop8jAemH,Omega,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
18,072RMxyaiPGuUfop8jAemH,Kike Boy,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
19,072RMxyaiPGuUfop8jAemH,High Density,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
20,072RMxyaiPGuUfop8jAemH,Megabass,Tecnologico III Megamix / Tonight / C'est Si B...,reggaeton,2014
21,4YBFDSBQtoK2zUNsN9FTZg,Tess,The Second That You Sleep - Interphace Remix,reggaeton,2014
22,0OQ5SqE5KkpY639bq5uFFO,The Style Council,Shout To The Top,reggaeton,2014
23,5FIUKOSQ2kiE0ad7GxCrO9,Squeeze,Tempted,reggaeton,2014
24,4g0mYcIWlORX07UV3fwxzQ,Iggy Pop,Candy,reggaeton,2014
25,5eJdszTnAudulQT3zcvsrQ,The Nativos,Night Time,reggaeton,2014
26,2gENHmajLeR1vFSGCtkaLn,Jerry Daley,"Gold - ""F"" Mix",reggaeton,2014
27,48lpqgtWVMIgohPXykr0Q9,Brian Cross,The Emotions,reggaeton,2015
28,48lpqgtWVMIgohPXykr0Q9,Fat Synth,The Emotions,reggaeton,2015
29,3J3CmUhlNjqWaokvikdTXM,2001:Canarias,Comin Up Strong - Radio Cut,reggaeton,2015
30,7GAfhe7K6ZAp0J9ncdh5tD,2001:Canarias,Comin Up Strong - Sven-R-G vs. Bass-T Club Mix,reggaeton,2015
31,0iNU5DNKXowDDoBcggClv4,2 In A Room,Now,reggaeton,2015
32,1aQXvB2MrsoJznI5wldosb,Brian Cross,The Eyes,reggaeton,2015
33,1aQXvB2MrsoJznI5wldosb,Fat Synth,The Eyes,reggaeton,2015
34,3ob8TbTdg3zm0fe5KCGg30,Brian Cross,Secret,reggaeton,2015
35,3ob8TbTdg3zm0fe5KCGg30,Fat Synth,Secret,reggaeton,2015
36,2dU2I8cJAvg4v9uTKWmoot,Generis,Dreams,reggaeton,2015
37,20WRbAfJhdDpY5iP2xfCI3,Fiesta Pop,Año 2000,reggaeton,2015
38,4VoHWTKwdeejTOEDXG1QCc,Fiesta Pop,A Quien Le Importa,reggaeton,2015
39,0il4GDOrhu9x0NXboG5P7V,Korpus,Indie,reggaeton,2015

In [ ]:
import pandas as pd

In [ ]:
df1.to_csv("datos_reggaeton.csv", index=False)

In [ ]:
df2.to_csv("datos.csv", index=False)